### ISSUE TITLE
Hello, 当我修改头像后，发现后端返回给前端的 URL 无法被用户访问

### ISSUE THREAD

**Issue by linrilian** [xiaoyunjie/openvpn-cms-flask#11]
![image](https://user-images.githubusercontent.com/65593245/118236378-94edbf80-b4c8-11eb-8994-0fac70453724.png)

**Comment by xiaoyunjie** [comment]
此问题已经解决，代码已push
你可以在 openvpn-cms-flask/app/config/setting.py 添加 SITE_DOMAIN，指定访问api服务的url, 用于本地文件上传，域名或IP地址。

![image](https://user-images.githubusercontent.com/18340924/119251864-7af46100-bbdb-11eb-9778-3cfbdae3871c.png)
