### ISSUE TITLE
本项目不维护了吗?

### ISSUE THREAD

**Issue by andywang1011** [xiaoyunjie/openvpn-cms-flask#17]
后端安装后不能获取tokey

**Comment by xiaoyunjie** [comment]
具体报什么错误呢，贴一下报错，也可以在README中添加QQ

**Comment by andywang1011** [comment]
![image](https://user-images.githubusercontent.com/40266446/173731503-69e5e9dd-09d4-41dd-b0e7-dec29177f6ad.png)
![image](https://user-images.githubusercontent.com/40266446/173731550-44ea6144-f536-461e-8113-9720914eac14.png)

测试获取tokey,提示密码不能为空.

**Comment by andywang1011** [comment]
我的问题.感谢

**Comment by andywang1011** [comment]
另外能不能使用客户端能不能使用账号和密码认证,不需要证书?

**Comment by xiaoyunjie** [comment]
可以，这个是openvpn层的事情，可以自己修改一下openvpn的认证方式
