### ISSUE TITLE
默认密码

### ISSUE THREAD

**Issue by SuperMonkeyC1** [xiaoyunjie/openvpn-cms-flask#19]
老哥，默认密码是什么呀？

**Comment by xiaoyunjie** [comment]
***@***.***

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月19日 02:07 |
| 收件人 | xiaoyunjie/openvpn-cms-flask ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [xiaoyunjie/openvpn-cms-flask] 默认密码 (Issue #19) |

老哥，默认密码是什么呀？

**Comment by xiaoyunjie** [comment]
README已经标注
