### ISSUE TITLE
VPN部署问题

### ISSUE THREAD

**Issue by nine-city** [xiaoyunjie/openvpn-cms-flask#4]
openvpn安装之后还需要单独安装PAM Radius等插件吗?另外多台服务器的话可以统一管理吗

**Comment by xiaoyunjie** [comment]
不涉及PAM Radius插件，暂时不支持多台服务器管理

**Comment by nine-city** [comment]
emmm,那意思是Python是直接调用的openvpn的API进行操作的吗

**Comment by xiaoyunjie** [comment]
是的，README最后有API接口。
由于是前后端分离，所以如果想要同时管理多套openvpn系统，可以自己在改一改前端，接入多个后端就行

**Comment by nine-city** [comment]
非常感谢老哥.
