### ISSUE TITLE
lin函数找不到

### ISSUE THREAD

**Issue by a769110811** [xiaoyunjie/openvpn-cms-flask#5]
请问add_super.py脚本lin函数找不到怎么处理。

**Comment by xiaoyunjie** [comment]
安装 Lin-CMS==0.2.0b2 了没

**Comment by a769110811** [comment]
Lin-CMS 安装后后台装上去了&nbsp; 前台还有报错&nbsp; 可以加下您微信嘛？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jack.xiao"<notifications@github.com&gt;; 
发送时间: 2020年12月7日(星期一) 中午1:39
收件人: "xiaoyunjie/openvpn-cms-flask"<openvpn-cms-flask@noreply.github.com&gt;; 
抄送: "夜语欣空"<769110811@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xiaoyunjie/openvpn-cms-flask] lin函数找不到 (#5)





 
安装 Lin-CMS==0.2.0b2 了没

**Comment by xiaoyunjie** [comment]
README 有微信二维码
