### ISSUE TITLE
请问能否支持外置数据库呢？

### ISSUE THREAD

**Issue by linrilian** [xiaoyunjie/openvpn-cms-flask#9]

**Comment by xiaoyunjie** [comment]
可以，只要把代码中的数据库连接字符串改成外置的MySQL，同时/usr/local/bin 下面的 connect  和 disconnec 脚本中数据库地址改一下就行

**Comment by linrilian** [comment]
那我需要修改哪些 py 文件呢？ 貌似 app/config/secure.py 存在数据库相关的配置，是这里么

**Comment by xiaoyunjie** [comment]
/openvpn-cms-flask/app/config/secure.py  
/usr/local/bin/connect.sh
/usr/local/bin/disconnect.sh
这几个文件改一下
